### ISSUE TITLE
Diff percentage is wrong

### ISSUE THREAD

**Issue by alonfixler** [fiverr/statistician#2]
**Expected Behaviour**
In the following example diff is 0.01%

**Result**
diff is 1%

**Reproduce**
Please see first push in edit history of this pr:
![screen shot 2018-10-23 at 17 37 00](https://user-images.githubusercontent.com/37267423/47368407-469a2a80-d6ea-11e8-81bc-2b42b2d68131.png)

https://github.com/fiverr/gig_gallery_package/pull/81#issuecomment-432252157

**Comment by omrilotan** [comment]
Raw numbers:

| Before | After
| - | -
| `234194` | `234183`
